In [ ]:
import numpy as np

# Generate a synthetic 100x12 dataset
np.random.seed(42) # For reproducible results
data = np.random.rand(100, 12) * 100 # 100 rows, 12 features

print(data[:5])  # Show the first 5 rows to verify changes

[[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404 15.59945203
   5.80836122 86.61761458 60.11150117 70.80725778  2.05844943 96.99098522]
 [83.24426408 21.23391107 18.18249672 18.34045099 30.4242243  52.47564316
  43.19450186 29.12291402 61.18528947 13.94938607 29.21446485 36.63618433]
 [45.60699842 78.51759614 19.96737822 51.42344384 59.24145689  4.64504127
  60.75448519 17.05241237  6.5051593  94.88855373 96.56320331 80.83973481]
 [30.46137692  9.7672114  68.42330265 44.01524937 12.20382348 49.51769101
   3.43885211 90.93204021 25.87799816 66.25222844 31.17110761 52.00680212]
 [54.67102793 18.48544555 96.95846278 77.51328234 93.94989416 89.48273504
  59.78999788 92.1874235   8.84925021 19.59828624  4.52272889 32.53303308]]


In [ ]:
# Continuous columns indexes (Python index starting at 0)
continuous_columns = [4, 5, 6, 7]

# Convert each continuous column
for col in continuous_columns:
    # Calculate bin edges based on quartiles
    quartiles = np.percentile(data[:, col], [25, 50, 75])
    bin_edges = np.hstack(([data[:, col].min()], quartiles, data[:, col].max()))

    # Bin the data
    binned_data = np.digitize(data[:, col], bins=bin_edges, right=True)

    # (Optional) Convert binned data to categorical labels
    # Note: Adjust the labels based on your bin edges
    labels = ['Q1', 'Q2', 'Q3', 'Q4']
    categorical_data = np.array([labels[i-1] for i in binned_data])

    # Replace the original continuous data with categorical data
    # For simplicity in this example, I'm directly replacing the numerical bin indicators.
    # You could also replace them with string labels or use a separate structure.
    data[:, col] = binned_data

# Now your dataset `data` has the 4 continuous features converted into categorical data.
print(data[:5])  # Show the first 5 rows to verify changes


[[37.45401188 95.07143064 73.19939418 59.86584842  2.          1.
   1.          4.         60.11150117 70.80725778  2.05844943 96.99098522]
 [83.24426408 21.23391107 18.18249672 18.34045099  2.          3.
   2.          1.         61.18528947 13.94938607 29.21446485 36.63618433]
 [45.60699842 78.51759614 19.96737822 51.42344384  3.          1.
   3.          1.          6.5051593  94.88855373 96.56320331 80.83973481]
 [30.46137692  9.7672114  68.42330265 44.01524937  1.          3.
   1.          4.         25.87799816 66.25222844 31.17110761 52.00680212]
 [54.67102793 18.48544555 96.95846278 77.51328234  4.          4.
   3.          4.          8.84925021 19.59828624  4.52272889 32.53303308]]


In [ ]:
import numpy as np

n = 5
a = np.arange(n)
blacked = np.random.randint(0,5,2)
a[np.isin(a,blacked)]

np.random.choice(a)

2

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
blacked

array([0, 3])

array([ True, False, False,  True, False])

In [12]:
import torch

torch.randn((2,3))

tensor([[-0.0638,  0.8521, -1.2255],
        [-0.5718,  0.7706, -0.3264]])

In [19]:
a = torch.arange(5)
a = a.view(-1,1)
b = torch.arange(3)
b = b.view(-1,1)
c = a@b.T

In [20]:
a.shape

torch.Size([5, 1])

In [22]:
torch.einsum('ij->ji',c)

tensor([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4],
        [0, 2, 4, 6, 8]])

In [23]:
c

tensor([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4],
        [0, 3, 6],
        [0, 4, 8]])

In [24]:
torch.einsum('ij->',c)

tensor(30)

In [25]:
torch.einsum('ij->i',c)

tensor([ 0,  3,  6,  9, 12])

In [26]:
torch.einsum('ij->i',c)

tensor([ 0,  3,  6,  9, 12])

tensor([  0,  30,  60,  90, 120])

In [33]:
a.shape

torch.Size([5, 1])

In [35]:
c.shape

torch.Size([5, 3])

In [39]:
torch.einsum('ji,jk->ik',a,c)

tensor([[ 0, 30, 60]])

In [53]:
c = torch.randint(0,3,(3,3))
print(c)
torch.einsum('ii->',c)

tensor([[2, 1, 2],
        [1, 2, 0],
        [1, 2, 1]])


tensor(5)

In [54]:
torch.einsum('ii->i',c)

tensor([2, 2, 1])

In [57]:
torch.sqrt(torch.einsum('ij->',torch.einsum('ij,ij->ij',c,c)))

tensor(4.4721)